Views
OLIPLICHE/blogapp pull request #5
Opened 2021-12-17 18:14 UTC by OLIPLICHE

- I added the Views associated with the Models and Controllers.

2021-12-17 20:17 UTC, DanSam5K requested changes
# Hi @OLIPLICHE, ♻️ Required Changes ♻️
## Highlights 💥 💥 💥 
- [x] Great implementation on displaying the user details ✔️ 
- [x] All linter checks are passing ✔️ 
- [x] You really think it smartly using the form partials to render certain re-usable component ✔️ 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![ ](https://user-images.githubusercontent.com/64173189/128109485-382fcc99-cf3c-4534-a70a-51351dfd9b39.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Adding a more detailed guide to help users clone and get a local app up and running in their local machine since just cloning and running `rails s` and won't work and not all visitors will be developers, what do think?

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-17 20:17 UTC, DanSam5K commented on app/views/users/show.html.erb
> +<% end %>
- [x] What do you think, how we use some kind of #recent_post method to render the user's 3 most recent post.? it would be nice to implement that 🤝

2021-12-17 20:17 UTC, DanSam5K commented on app/views/posts/index.html.erb
> +<% end %>
- [x] We could also implement a #recent_comment method to display the comments based on the most recent comment in the case of the post also. [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md)

2021-12-17 21:26 UTC, OLIPLICHE commented on app/views/users/show.html.erb
> +<% end %>
Done

2021-12-17 23:22 UTC, OLIPLICHE commented on app/views/posts/index.html.erb
> +<% end %>
Done

2021-12-17 23:54 UTC, Dipeshtwis requested changes
Hi @OLIPLICHE, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️

- [ ] Still, we can't see the proper steps to run the project locally. Please include the steps in the README.

```
$ git clone https://github.com/OLIPLICHE/blogapp.git
$ cd blogapp
$ bundle
$ rails db:create
$ rails db:migrate
$ npm i
$ rails s
```

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-18 00:15 UTC, OLIPLICHE commented
I have Updated my Readme file. Thank you. Please write me on slack if there is another change to make because This is my last request review.

2021-12-18 00:18 UTC, sinansevgi approved these changes
# Approved :heavy_check_mark: 

Hi @OLIPLICHE, 

There is nothing to say :+1: 
Your project is complete!  
Congratulations! 🎉

You can merge this pull request and continue with your journey :wave: 


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-18 00:19 UTC, merged